services:
  postgres:
    image: postgres:16-alpine
    container_name: bifrostauth-db
    environment:
      POSTGRES_DB: authsti
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d authsti"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: bifrostauth:latest
    container_name: bifrostauth
    env_file:
      - .env.bifrostauth
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  postgres_data:
